services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    volumes:
      - ./python:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - internal

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend  # Kontext ist der Ordner, in dem sich das Dockerfile befindet
    container_name: frontend
    working_dir: /var/www/html/app/  # Das Arbeitsverzeichnis im Container
    ports:
      - "5173:5173"  # Port weiterleiten
    volumes:
      - ./frontend:/var/www/html/app  # Mounten nur des frontend-Ordners in den Container
    networks:
      - internal  # Netzwerk, das du eventuell verwendest (falls du mehrere Services hast)

  database:
    image: mariadb:10.5
    container_name: symfony_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - internal
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8002:80"
    depends_on:
      - database
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
